#!/bin/bash

echo "🔍 Checking API Health on Production"
echo "===================================="
echo ""
echo "Run these commands on your production server:"
echo ""
echo "1. Check if Next.js is running properly:"
echo "   pm2 status"
echo ""
echo "2. Check recent PM2 logs for errors:"
echo "   pm2 logs skyward-prod --lines 50 | grep -E '(error|Error|ERROR|failed|Failed)'"
echo ""
echo "3. Test if the app is responding:"
echo "   curl -I http://localhost:3000/"
echo ""
echo "4. Test the API endpoint with verbose output:"
echo "   curl -v 'http://localhost:3000/api/sitemap-parts?limit=10&offset=0'"
echo ""
echo "5. Check if the API route file exists and is accessible:"
echo "   ls -la /home/ec2-user/fe/src/app/api/sitemap-parts/"
echo "   ls -la /home/ec2-user/fe/.next/server/app/api/sitemap-parts/"
echo ""
echo "6. Try restarting the app:"
echo "   pm2 restart skyward-prod"
echo "   # Wait 30 seconds for startup"
echo "   curl -s 'http://localhost:3000/api/sitemap-parts?limit=10&offset=0' | jq ."
echo ""
echo "7. Check for build issues:"
echo "   cd /home/ec2-user/fe"
echo "   npm run build"