#!/bin/bash

echo "🔍 Diagnosing Sitemap Issues on Production Server"
echo "================================================"
echo ""
echo "Run these commands on your production server to diagnose:"
echo ""
echo "1. Check what's in the sitemap API route:"
echo "   cat /home/ec2-user/fe/src/app/api/sitemap-parts/route.ts | head -20"
echo ""
echo "2. Test the sitemap API directly:"
echo "   curl -s 'http://localhost:3000/api/sitemap-parts?limit=10&offset=0' | jq ."
echo ""
echo "3. Test a problematic range:"
echo "   curl -s 'http://localhost:3000/api/sitemap-parts?limit=2000&offset=720000' | jq ."
echo ""
echo "4. Check for any backup files:"
echo "   ls -la /home/ec2-user/fe/src/app/api/sitemap-parts/"
echo ""
echo "5. Check database connections during timeout:"
echo "   # While a sitemap request is timing out, run:"
echo "   psql -h skywardnew.cjwsewswq7sh.us-east-2.rds.amazonaws.com -U postgres -d skyward -c \"SELECT pid, state, query_start, now() - query_start as duration, query FROM pg_stat_activity WHERE state = 'active' ORDER BY duration DESC LIMIT 10;\""
echo ""
echo "6. Check if the disable script was run:"
echo "   grep -n 'TEMPORARILY DISABLED' /home/ec2-user/fe/src/app/api/sitemap-parts/route.ts"